export const {
  VITE_API_URL: API_URL,
  VITE_AUTH0_DOMAIN: AUTH0_DOMAIN,
  VITE_AUTH0_CLIENT_ID: AUTH0_CLIENT_ID,
  VITE_AUTH0_AUDIENCE: AUTH0_AUDIENCE,
  VITE_SAFE_ADDRESS: SAFE_ADDRESS,
  VITE_WXTM_TOKEN_ADDRESS: WXTM_TOKEN_ADDRESS,
  VITE_NETWORK_ID: NETWORK_ID,
} = import.meta.env;
