export const {
  VITE_API_URL: API_URL,
  VITE_AUTH0_DOMAIN: AUTH0_DOMAIN,
  VITE_AUTH0_CLIENT_ID: AUTH0_CLIENT_ID,
  VITE_AUTH0_AUDIENCE: AUTH0_AUDIENCE,
  VITE_SAFE_ADDRESS: SAFE_ADDRESS,
  VITE_SAFE_API_BASE_URL: SAFE_API_BASE_URL,
} = import.meta.env;
